(alias angle chez-angle)
(alias imag-part chez-imag-part)
(alias magnitude chez-magnitude)
(alias make-polar chez-make-polar)
(alias make-rectangular chez-make-rectangular)
(alias real-part chez-real-part)
